name: GoldDropRemover
version: ${project.version}
description: ${project.description}
api-version: '1.13'
author: Karl Essinger (KarlofDuty)
website: http://karlofduty.com
main: com.karlofduty.GoldDropRemover.GoldDropRemover